### ISSUE TITLE
`oci_image` still uses `jq`

### ISSUE THREAD

**Issue by smndtrl** [bazel-contrib/rules_oci#260] opened 2023-06-05 14:46 UTC
`jq` and `arm64` has some compat issues in `@aspect_bazel_lib//lib:jq_toolchain_type`. [see aspect](https://github.com/aspect-build/bazel-lib/issues/268)

I only spent 10 minutes following a tutorial and an hour debugging. My `bazel` experience is limited to that, so I feel like I can't make a PR for that.

https://github.com/bazel-contrib/rules_oci/blob/e426977dcf6bba3017cdc6bb8b1aeca7bc35b1d5/oci/private/image.bzl#L191

**Comment by chancila** [comment] 2023-06-05 17:26
https://github.com/bazel-contrib/rules_oci/issues/253

**Comment by thesayyn** [comment] 2023-06-09 17:56
closing this as duplicate of https://github.com/bazel-contrib/rules_oci/issues/253

**Closed by thesayyn** 2023-06-09 17:56 UTC
