### ISSUE TITLE
Multi arch indices broken in v2alpha5

### ISSUE THREAD

**Issue by juanzolotoochin** [bazel-contrib/rules_oci#639] opened 2024-06-25 23:37 UTC
For the following target:

```
$ bazel query --output=build //bazel/examples/oci/publish_vservice_go_image:_publish.index

# /home/juan-munoz/gg/repo/bazel/examples/oci/publish_vservice_go_image/BUILD.bazel:17:26
oci_image_index(
  name = "_publish.index",
  tags = ["manual"],
  generator_name = "publish",
  generator_function = "publish_vservice_go_image",
  generator_location = "bazel/examples/oci/publish_vservice_go_image/BUILD.bazel:17:26",
  images = ["//bazel/examples/oci/publish_vservice_go_image:_publish.amd64", "//bazel/examples/oci/publish_vservice_go_image:_publish.arm64"],
)
# Rule _publish.index instantiated at (most recent call last):
#   /home/juan-munoz/gg/repo/bazel/examples/oci/publish_vservice_go_image/BUILD.bazel:17:26 in <toplevel>
#   /home/juan-munoz/gg/repo/bazel/oci/service.bzl:89:27                                    in publish_vservice_go_image
#   /home/juan-munoz/gg/repo/bazel/oci/service.bzl:47:18                                    in publish_vservice_image
#   /home/juan-munoz/gg/repo/bazel/oci/oci.bzl:235:24                                       in publish_image
# Rule oci_image_index defined at (most recent call last):
#   /home/juan-munoz/.cache/bazel/_bazel_juan-munoz/5e2ab9bef16b62dfdad15ea9f3634c69/external/rules_oci/oci/private/image_index.bzl:75:23 in <toplevel
```

Which is just an `oci_index` with two images: `arm64` and `amd64`. When building the index:

```
bazel build //bazel/examples/oci/publish_vservice_go_image:_publish.index

Target //bazel/examples/oci/publish_vservice_go_image:_publish.index up-to-date:
  bazel-bin/bazel/examples/oci/publish_vservice_go_image/_publish.index
````

The output produced only has one of the two images:
```
# Find the manifest in the output
cat bazel-bin/bazel/examples/oci/publish_vservice_go_image/_publish.index/index.json
{
  "manifests": [
    {
      "mediaType": "application/vnd.oci.image.index.v1+json",
      "size": 375,
      "digest": "sha256:547ab32ced98b7107f22c7a2d79d1f25ecb1cc46bdf308287d1561896d63cdee"
    }
  ]
}

# That blob is the one we want. We can see it only contains the `arm64` image:
cat bazel-bin/bazel/examples/oci/publish_vservice_go_image/_publish.index/blobs/sha256/547ab32ced98b7107f22c7a2d79d1f25ecb1cc46bdf308287d1561896d63cdee
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.index.v1+json",
  "manifests": [
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:49bfe0fa65600ddbc8ed3d28cbb97c9474ec6d9f395583ae10b6206f92d4f0d2",
      "size": 853,
      "platform": {
        "os": "linux",
        "architecture": "arm64"
      }
    }
  ]
```

Compare with doing the same but in `rules_oci@v1`:

```
$  cat bazel-bin/bazel/examples/oci/publish_vservice_go_image/_publish.index/index.json
{
  "schemaVersion": 2,
  "manifests": [
    {
      "mediaType": "application/vnd.oci.image.index.v1+json",
      "size": 646,
      "digest": "sha256:5ef7438421b55cf126d3c7500f50a8e29199e10c2fb9341382316681e029a9ce"
    }
  ]
}

$ cat bazel-bin/bazel/examples/oci/publish_vservice_go_image/_publish.index/blobs/sha256/5ef7438421b55cf126d3c7500f50a8e29199e10c2fb9341382316681e029a9ce
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.index.v1+json",
  "manifests": [
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "size": 717,
      "digest": "sha256:c0c5dd9d8253f5fdaaf1ac454e4d8a712a3d8fecc9b62cb7cceacf9439d172fd",
      "platform": {
        "os": "linux",
        "architecture": "amd64"
      }
    },
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "size": 717,
      "digest": "sha256:15523c5a7adf9f7646eacc51111caaeafb38dcbf29a894e26eb6c326363efe75",
      "platform": {
        "os": "linux",
        "architecture": "arm64"
      }
    }
  ]
}
```

Subsequently, when pushing to a remote registry, the index only contains a single image in v2, not both as it does in v1.

**Comment by juanzolotoochin** [comment] 2024-06-25 23:42
This may be a duplicate of https://github.com/bazel-contrib/rules_oci/issues/638

**Comment by thesayyn** [comment] 2024-06-26 10:54
Closing as duplicate of https://github.com/bazel-contrib/rules_oci/issues/638

**Closed by thesayyn** 2024-06-26 10:54 UTC
