### ISSUE TITLE
Add direct variables expansion support in oci_push

### ISSUE THREAD

**Issue by gfrankliu** [bazel-contrib/rules_oci#628] opened 2024-06-16 03:49 UTC
https://github.com/bazel-contrib/rules_oci/issues/512 is closed with the workaround of using "expand_template".
Can we have a feature request to support variable expansion directly in "oci_push", similar to "container_push", so we don't have to rely on the workaround?

**Comment by thesayyn** [comment] 2024-06-16 10:40
Its not a workaround that's how we implemented stamping in rules_oci.

**Comment by gfrankliu** [comment] 2024-06-16 13:34
I'm not talking about stamping, but just passing a variable to oci_push, eg: bazel run --define repo_url ...

**Comment by gfrankliu** [comment] 2024-06-16 17:24
When `container_push`, we can have the BUILD file:

```
container_push(
    name = "image-push",
    format = "OCI",
    image = ":image",
    registry = "$(REGISTRY_REGION)-docker.pkg.dev",
    repository = "$(REGISTRY_PROJECT_ID)/dev-repo/myapp",
    tag = "$(IMAGE_TAG)",
    visibility = ["//visibility:public"],
)
```

and run
```
bazel run -define=REGISTRY_REGION=us --define=REGISTRY_PROJECT_ID=my-project-id   --define=IMAGE_TAG=test-tag :image-push
```

I tried below with `oci_push` but the variable expansion doesn't work. 

```
oci_push(
    name = "image-push",
    image = ":image",
    repository = "$(REGISTRY_REGION)-docker.pkg.dev/$(REGISTRY_PROJECT_ID)/dev-repo/myapp",
    remote_tags = ["$(IMAGE_TAG)"],
    visibility = ["//visibility:public"],
)
```

The only workaround seems to be using "expand_template" at this time. It would be great if we can add direct variable expansion support in `oci_push`, like `container_push`.

**Comment by thesayyn** [comment] 2024-06-17 08:42
it's the same thing essentially, expand_template also supports define variables, so you can expand your `--define` values.

**Comment by gfrankliu** [comment] 2024-06-17 15:39
Yes, currently since oci_push doesn't support variable expansion, we have to use variable expansion in expand_template to workaround that. Today we use container_push with variables. Is it possible to add variable expansion support in oci_push directly so we don't have to add expand_template for every oci_push during migration?

**Comment by thesayyn** [comment] 2024-06-17 16:54
This is by design, is how it works, and not a workaround. Is it unusual? Yes, but it saves us a lot of maintainer time.  
> we don't have to add expand_template for every oci_push during migration

It's clearly written on the Readme that we are not trying to be 1:1 replacement for rules_docker. 

An alternative you can use is that, creating a macro around `oci_push` that automatically stamps `repository` and `repo_tags` so you don't have to use expand template everywhere. It's up to you at that point, how you want to stamp these variables.

**Comment by thesayyn** [comment] 2024-07-08 13:28
Closing this as there is nothing to fix here.

**Closed by thesayyn** 2024-07-08 13:28 UTC
Labels: question, can close?, works as intended
