### ISSUE TITLE
Error pulling

### ISSUE THREAD

**Issue by danielepolencic** [bazel-contrib/rules_oci#87] opened 2023-03-02 12:06 UTC
I'm testing `rules_oci` with `rules_js` (and specifically `js_image`).

The build currently fails with:

```
[4,897 / 4,899] [Prepa] JsImageLayer //:layers
[4,897 / 4,899] JsImageLayer //:layers; 11s linux-sandbox, remote-cache
ERROR: /home/runner/work/noderosso/noderosso/BUILD.bazel:38:10: OCI Image //:server failed: (Exit 1): image_server.sh failed: error executing command bazel-out/k8-fastbuild/bin/image_server.sh mutate oci:layout/bazel-out/k8-fastbuild/bin/external/nodejs_base_image/layout --tag oci:registry/server '--append=bazel-out/k8-fastbuild/bin/layers_app.tar.gz' ... (remaining 6 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
HTTP port 0
{"level":"info","params":{"distSpecVersion":"1.0.1-dev","GoVersion":"go1.19.1","Commit":"v1.4.3-rc3-0-gfd87a22","ReleaseTag":"v1.4.3-rc3","BinaryType":"-sync-search-scrub-metrics-lint","AccessControl":null,"Storage":{"Dedupe":true,"GC":true,"Commit":false,"GCDelay":3600000000000,"GCInterval":0,"RootDirectory":"bazel-out/k8-fastbuild/bin//storage_server","StorageDriver":null,"SubPaths":null},"HTTP":{"Address":"127.0.0.1","Port":"0","AllowOrigin":"","TLS":null,"Auth":{"FailDelay":0,"HTPasswd":{"Path":""},"LDAP":null,"Bearer":null},"RawAccessControl":null,"Realm":"","Ratelimit":null},"Log":{"Level":"info","Output":"","Audit":""},"Extensions":null},"goroutine":1,"caller":"zotregistry.io/zot/pkg/api/controller.go:116","time":"2023-03-02T11:53:30.758333746Z","message":"configuration settings"}
{"level":"info","cpus":2,"max. open files":65536,"listen backlog":"4096","max. inotify watches":"2147483647","goroutine":1,"caller":"zotregistry.io/zot/pkg/api/controller.go:107","time":"2023-03-02T11:53:30.758474147Z","message":"runtime params"}
{"level":"warn","goroutine":1,"caller":"zotregistry.io/zot/pkg/debug/swagger/swagger_disabled.go:21","time":"2023-03-02T11:53:30.789056104Z","message":"skipping enabling swagger because given zot binarydoesn't include this feature, please build a binary that does so"}
{"level":"info","port":36345,"address":"127.0.0.1","goroutine":1,"caller":"zotregistry.io/zot/pkg/api/controller.go:193","time":"2023-03-02T11:53:30.789251407Z","message":"port is unspecified, listening on kernel chosen port"}
{"level":"info","module":"http","clientIP":"127.0.0.1:57384","method":"GET","path":"/v2/","statusCode":200,"latency":"13.1µs","bodySize":0,"headers":{"Accept-Encoding":["gzip"],"User-Agent":["crane/0.12.0 go-containerregistry/0.12.0"]},"goroutine":37,"caller":"zotregistry.io/zot/pkg/api/session.go:132","time":"2023-03-02T11:53:30.799068421Z","message":"HTTP API"}
{"level":"error","error":"stat bazel-out/k8-fastbuild/bin/storage_server/oci/layout/blobs/sha256/aa2b1da47449b03ef99af1db40df44102754f419d4f72581df468ffcd360bc70: no such file or directory","blob":"bazel-out/k8-fastbuild/bin/storage_server/oci/layout/blobs/sha256/aa2b1da47449b03ef99af1db40df44102754f419d4f72581df468ffcd360bc70","goroutine":37,"caller":"zotregistry.io/zot/pkg/storage/local/local.go:1070","time":"2023-03-02T11:53:30.799758829Z","caller":"zotregistry.io/zot/pkg/storage/local/local.go:1070","message":"failed to stat blob"}
{"level":"error","error":"cache: miss","digest":"sha256:aa2b1da47449b03ef99af1db40df44102754f419d4f72581df468ffcd360bc70","goroutine":37,"caller":"zotregistry.io/zot/pkg/storage/local/local.go:1075","time":"2023-03-02T11:53:30.79981543Z","caller":"zotregistry.io/zot/pkg/storage/local/local.go:1075","message":"cache: not found"}
{"level":"info","module":"http","clientIP":"127.0.0.1:57384","method":"HEAD","path":"/v2/oci/layout/blobs/sha256:aa2b1da47449b03ef99af1db40df44102754f419d4f72581df468ffcd360bc70","statusCode":404,"latency":"367.005µs","bodySize":407,"headers":{"User-Agent":["crane/0.12.0 go-containerregistry/0.12.0"]},"goroutine":37,"caller":"zotregistry.io/zot/pkg/api/session.go:132","time":"2023-03-02T11:53:30.800063033Z","message":"HTTP API"}
{"level":"error","error":"stat bazel-out/k8-fastbuild/bin/storage_server/oci/layout/blobs/sha256/7dcffaf987694bb0a0863ae2c3b582125b1c20d3148f0412f901b918b9a8e22d: no such file or directory","blob":"bazel-out/k8-fastbuild/bin/storage_server/oci/layout/blobs/sha256/7dcffaf987694bb0a0863ae2c3b582125b1c20d3148f0412f901b918b9a8e22d","goroutine":42,"caller":"zotregistry.io/zot/pkg/storage/local/local.go:1070","time":"2023-03-02T11:53:30.800282636Z","caller":"zotregistry.io/zot/pkg/storage/local/local.go:1070","message":"failed to stat blob"}
{"level":"error","error":"cache: miss","digest":"sha256:7dcffaf987694bb0a0863ae2c3b582125b1c20d3148f0412f901b918b9a8e22d","goroutine":42,"caller":"zotregistry.io/zot/pkg/storage/local/local.go:1075","time":"2023-03-02T11:53:30.800323536Z","caller":"zotregistry.io/zot/pkg/storage/local/local.go:1075","message":"cache: not found"}
{"level":"info","module":"http","clientIP":"127.0.0.1:57420","method":"HEAD","path":"/v2/oci/layout/blobs/sha256:7dcffaf987694bb0a0863ae2c3b582125b1c20d3148f0412f901b918b9a8e22d","statusCode":404,"latency":"122.401µs","bodySize":407,"headers":{"User-Agent":["crane/0.12.0 go-containerregistry/0.12.0"]},"goroutine":42,"caller":"zotregistry.io/zot/pkg/api/session.go:132","time":"2023-03-02T11:53:30.800383337Z","message":"HTTP API"}
{"level":"error","error":"stat bazel-out/k8-fastbuild/bin/storage_server/oci/layout/blobs/sha256/8fa73d8e9b247843c662dbf1f1e26a211ca0f8121d4fd858868ed10adc921b1e: no such file or directory","blob":"bazel-out/k8-fastbuild/bin/storage_server/oci/layout/blobs/sha256/8fa73d8e9b247843c662dbf1f1e26a211ca0f8121d4fd858868ed10adc921b1e","goroutine":39,"caller":"zotregistry.io/zot/pkg/storage/local/local.go:1070","time":"2023-03-02T11:53:30.800542039Z","caller":"zotregistry.io/zot/pkg/storage/local/local.go:1070","message":"failed to stat blob"}
{"level":"error","error":"cache: miss","digest":"sha256:8fa73d8e9b247843c662dbf1f1e26a211ca0f8121d4fd858868ed10adc921b1e","goroutine":39,"caller":"zotregistry.io/zot/pkg/storage/local/local.go:1075","time":"2023-03-02T11:53:30.800581239Z","caller":"zotregistry.io/zot/pkg/storage/local/local.go:1075","message":"cache: not found"}
{"level":"info","module":"http","clientIP":"127.0.0.1:57400","method":"HEAD","path":"/v2/oci/layout/blobs/sha256:8fa73d8e9b247843c662dbf1f1e26a211ca0f8121d4fd858868ed10adc921b1e","statusCode":404,"latency":"106.201µs","bodySize":407,"headers":{"User-Agent":["crane/0.12.0 go-containerregistry/0.12.0"]},"goroutine":39,"caller":"zotregistry.io/zot/pkg/api/session.go:132","time":"2023-03-02T11:53:30.80062624Z","message":"HTTP API"}
{"level":"error","error":"stat bazel-out/k8-fastbuild/bin/storage_server/oci/layout/blobs/sha256/383e1c5dd0c1830143b1230e90292ebd4219911e0512b70d250c8907c4899110: no such file or directory","blob":"bazel-out/k8-fastbuild/bin/storage_server/oci/layout/blobs/sha256/383e1c5dd0c1830143b1230e90292ebd4219911e0512b70d250c8907c4899110","goroutine":40,"caller":"zotregistry.io/zot/pkg/storage/local/local.go:1070","time":"2023-03-02T11:53:30.800749741Z","caller":"zotregistry.io/zot/pkg/storage/local/local.go:1070","message":"failed to stat blob"}
{"level":"error","error":"cache: miss","digest":"sha256:383e1c5dd0c1830143b1230e90292ebd4219911e0512b70d250c8907c4899110","goroutine":40,"caller":"zotregistry.io/zot/pkg/storage/local/local.go:1075","time":"2023-03-02T11:53:30.800786141Z","caller":"zotregistry.io/zot/pkg/storage/local/local.go:1075","message":"cache: not found"}
{"level":"info","module":"http","clientIP":"127.0.0.1:57404","method":"HEAD","path":"/v2/oci/layout/blobs/sha256:383e1c5dd0c1830143b1230e90292ebd4219911e0512b70d250c8907c4899110","statusCode":404,"latency":"93.701µs","bodySize":407,"headers":{"User-Agent":["crane/0.12.0 go-containerregistry/0.12.0"]},"goroutine":40,"caller":"zotregistry.io/zot/pkg/api/session.go:132","time":"2023-03-02T11:53:30.800827142Z","message":"HTTP API"}
{"level":"error","error":"stat bazel-out/k8-fastbuild/bin/storage_server/oci/layout/blobs/sha256/c59673e9fae3f9d588110a25acdf7240f3a5d97c40fb86ccc71c23bf7abbea53: no such file or directory","blob":"bazel-out/k8-fastbuild/bin/storage_server/oci/layout/blobs/sha256/c59673e9fae3f9d588110a25acdf7240f3a5d97c40fb86ccc71c23bf7abbea53","goroutine":41,"caller":"zotregistry.io/zot/pkg/storage/local/local.go:1070","time":"2023-03-02T11:53:30.800945043Z","caller":"zotregistry.io/zot/pkg/storage/local/local.go:1070","message":"failed to stat blob"}
{"level":"error","error":"cache: miss","digest":"sha256:c59673e9fae3f9d588110a25acdf7240f3a5d97c40fb86ccc71c23bf7abbea53","goroutine":41,"caller":"zotregistry.io/zot/pkg/storage/local/local.go:1075","time":"2023-03-02T11:53:30.800981544Z","caller":"zotregistry.io/zot/pkg/storage/local/local.go:1075","message":"cache: not found"}
{"level":"info","module":"http","clientIP":"127.0.0.1:57410","method":"HEAD","path":"/v2/oci/layout/blobs/sha256:c59673e9fae3f9d588110a25acdf7240f3a5d97c40fb86ccc71c23bf7abbea53","statusCode":404,"latency":"103.801µs","bodySize":407,"headers":{"User-Agent":["crane/0.12.0 go-containerregistry/0.12.0"]},"goroutine":41,"caller":"zotregistry.io/zot/pkg/api/session.go:132","time":"2023-03-02T11:53:30.801030444Z","message":"HTTP API"}
{"level":"info","module":"http","clientIP":"127.0.0.1:57384","method":"POST","path":"/v2/oci/layout/blobs/uploads/","statusCode":202,"latency":"281.804µs","bodySize":0,"headers":{"Accept-Encoding":["gzip"],"Content-Length":["0"],"Content-Type":["application/json"],"User-Agent":["crane/0.12.0 go-containerregistry/0.12.0"]},"goroutine":37,"caller":"zotregistry.io/zot/pkg/api/session.go:132","time":"2023-03-02T11:53:30.801444749Z","message":"HTTP API"}
{"level":"info","module":"http","clientIP":"127.0.0.1:57410","method":"POST","path":"/v2/oci/layout/blobs/uploads/","statusCode":202,"latency":"57.7µs","bodySize":0,"headers":{"Accept-Encoding":["gzip"],"Content-Length":["0"],"Content-Type":["application/json"],"User-Agent":["crane/0.12.0 go-containerregistry/0.12.0"]},"goroutine":41,"caller":"zotregistry.io/zot/pkg/api/session.go:132","time":"2023-03-02T11:53:30.801859054Z","message":"HTTP API"}
{"level":"info","module":"http","clientIP":"127.0.0.1:57420","method":"POST","path":"/v2/oci/layout/blobs/uploads/","statusCode":202,"latency":"38.501µs","bodySize":0,"headers":{"Accept-Encoding":["gzip"],"Content-Length":["0"],"Content-Type":["application/json"],"User-Agent":["crane/0.12.0 go-containerregistry/0.12.0"]},"goroutine":42,"caller":"zotregistry.io/zot/pkg/api/session.go:132","time":"2023-03-02T11:53:30.802028756Z","message":"HTTP API"}
{"level":"info","module":"http","clientIP":"127.0.0.1:57400","method":"POST","path":"/v2/oci/layout/blobs/uploads/","statusCode":202,"latency":"34.5µs","bodySize":0,"headers":{"Accept-Encoding":["gzip"],"Content-Length":["0"],"Content-Type":["application/json"],"User-Agent":["crane/0.12.0 go-containerregistry/0.12.0"]},"goroutine":39,"caller":"zotregistry.io/zot/pkg/api/session.go:132","time":"2023-03-02T11:53:30.802168258Z","message":"HTTP API"}
{"level":"info","module":"http","clientIP":"127.0.0.1:57384","method":"PATCH","path":"/v2/oci/layout/blobs/uploads/d433157d-3c5f-404f-9db7-b7095e44ecbf","statusCode":202,"latency":"75.601µs","bodySize":0,"headers":{"Accept-Encoding":["gzip"],"Content-Type":["application/octet-stream"],"User-Agent":["crane/0.12.0 go-containerregistry/0.12.0"]},"goroutine":37,"caller":"zotregistry.io/zot/pkg/api/session.go:132","time":"2023-03-02T11:53:30.802423961Z","message":"HTTP API"}
{"level":"info","module":"http","clientIP":"127.0.0.1:57420","method":"PATCH","path":"/v2/oci/layout/blobs/uploads/a5dc1a29-3a2c-4e69-827b-542b0f0ee9be","statusCode":202,"latency":"928.31µs","bodySize":0,"headers":{"Accept-Encoding":["gzip"],"Content-Type":["application/octet-stream"],"User-Agent":["crane/0.12.0 go-containerregistry/0.12.0"]},"goroutine":42,"caller":"zotregistry.io/zot/pkg/api/session.go:132","time":"2023-03-02T11:53:30.807849924Z","message":"HTTP API"}
{"level":"info","module":"http","clientIP":"127.0.0.1:57404","method":"POST","path":"/v2/oci/layout/blobs/uploads/","statusCode":202,"latency":"101.401µs","bodySize":0,"headers":{"Accept-Encoding":["gzip"],"Content-Length":["0"],"Content-Type":["application/json"],"User-Agent":["crane/0.12.0 go-containerregistry/0.12.0"]},"goroutine":40,"caller":"zotregistry.io/zot/pkg/api/session.go:132","time":"2023-03-02T11:53:30.808785335Z","message":"HTTP API"}
{"level":"info","r.ContentLength":0,"goroutine":42,"caller":"zotregistry.io/zot/pkg/api/routes.go:1143","time":"2023-03-02T11:53:30.80923554Z","message":"DEBUG"}
{"level":"info","r.ContentLength":0,"goroutine":37,"caller":"zotregistry.io/zot/pkg/api/routes.go:1143","time":"2023-03-02T11:53:30.813884094Z","message":"DEBUG"}
{"level":"info","module":"http","clientIP":"127.0.0.1:57420","method":"PUT","path":"/v2/oci/layout/blobs/uploads/a5dc1a29-3a2c-4e69-827b-542b0f0ee9be?digest=sha256%3A7dcffaf987694bb0a0863ae2c3b582125b1c20d3148f0412f901b918b9a8e22d","statusCode":201,"latency":"12.83735ms","bodySize":0,"headers":{"Accept-Encoding":["gzip"],"Content-Length":["0"],"Content-Type":["application/octet-stream"],"User-Agent":["crane/0.12.0 go-containerregistry/0.12.0"]},"goroutine":42,"caller":"zotregistry.io/zot/pkg/api/session.go:132","time":"2023-03-02T11:53:30.822146191Z","message":"HTTP API"}
{"level":"info","module":"http","clientIP":"127.0.0.1:57384","method":"PUT","path":"/v2/oci/layout/blobs/uploads/d433157d-3c5f-404f-9db7-b7095e44ecbf?digest=sha256%3Aaa2b1da47449b03ef99af1db40df44102754f419d4f72581df468ffcd360bc70","statusCode":201,"latency":"12.80045ms","bodySize":0,"headers":{"Accept-Encoding":["gzip"],"Content-Length":["0"],"Content-Type":["application/octet-stream"],"User-Agent":["crane/0.12.0 go-containerregistry/0.12.0"]},"goroutine":37,"caller":"zotregistry.io/zot/pkg/api/session.go:132","time":"2023-03-02T11:53:30.822192792Z","message":"HTTP API"}
{"level":"info","module":"http","clientIP":"127.0.0.1:57404","method":"PATCH","path":"/v2/oci/layout/blobs/uploads/5921f2e1-1125-4e06-93ad-a76f851a97b2","statusCode":202,"latency":"9.034806ms","bodySize":0,"headers":{"Accept-Encoding":["gzip"],"Content-Type":["application/octet-stream"],"User-Agent":["crane/0.12.0 go-containerregistry/0.12.0"]},"goroutine":40,"caller":"zotregistry.io/zot/pkg/api/session.go:132","time":"2023-03-02T11:53:30.82381451Z","message":"HTTP API"}
2023/03/02 11:53:30 pushed blob: sha256:7dcffaf987694bb0a0863ae2c3b582125b1c20d3148f0412f901b918b9a8e22d
{"level":"info","r.ContentLength":0,"goroutine":40,"caller":"zotregistry.io/zot/pkg/api/routes.go:1143","time":"2023-03-02T11:53:30.826243939Z","message":"DEBUG"}
2023/03/02 11:53:30 pushed blob: sha256:aa2b1da47449b03ef99af1db40df44102754f419d4f72581df468ffcd360bc70
{"level":"info","module":"http","clientIP":"127.0.0.1:57410","method":"PATCH","path":"/v2/oci/layout/blobs/uploads/68e7678d-79e2-4715-92d3-eb55a47b2c66","statusCode":202,"latency":"27.284918ms","bodySize":0,"headers":{"Accept-Encoding":["gzip"],"Content-Type":["application/octet-stream"],"User-Agent":["crane/0.12.0 go-containerregistry/0.12.0"]},"goroutine":41,"caller":"zotregistry.io/zot/pkg/api/session.go:132","time":"2023-03-02T11:53:30.829949082Z","message":"HTTP API"}
{"level":"info","r.ContentLength":0,"goroutine":37,"caller":"zotregistry.io/zot/pkg/api/routes.go:1143","time":"2023-03-02T11:53:30.831828904Z","message":"DEBUG"}
{"level":"info","module":"http","clientIP":"127.0.0.1:57404","method":"PUT","path":"/v2/oci/layout/blobs/uploads/5921f2e1-1125-4e06-93ad-a76f851a97b2?digest=sha256%3A383e1c5dd0c1830143b1230e90292ebd4219911e0512b70d250c8907c4899110","statusCode":201,"latency":"12.252043ms","bodySize":0,"headers":{"Accept-Encoding":["gzip"],"Content-Length":["0"],"Content-Type":["application/octet-stream"],"User-Agent":["crane/0.12.0 go-containerregistry/0.12.0"]},"goroutine":40,"caller":"zotregistry.io/zot/pkg/api/session.go:132","time":"2023-03-02T11:53:30.838499082Z","message":"HTTP API"}
2023/03/02 11:53:30 pushed blob: sha256:383e1c5dd0c1830143b1230e90292ebd4219911e0512b70d250c8907c4899110
{"level":"info","module":"http","clientIP":"127.0.0.1:57384","method":"PUT","path":"/v2/oci/layout/blobs/uploads/68e7678d-79e2-4715-92d3-eb55a47b2c66?digest=sha256%3Ac59673e9fae3f9d588110a25acdf7240f3a5d97c40fb86ccc71c23bf7abbea53","statusCode":201,"latency":"31.128664ms","bodySize":0,"headers":{"Accept-Encoding":["gzip"],"Content-Length":["0"],"Content-Type":["application/octet-stream"],"User-Agent":["crane/0.12.0 go-containerregistry/0.12.0"]},"goroutine":37,"caller":"zotregistry.io/zot/pkg/api/session.go:132","time":"2023-03-02T11:53:30.862984668Z","message":"HTTP API"}
2023/03/02 11:53:30 pushed blob: sha256:c59673e9fae3f9d588110a25acdf7240f3a5d97c40fb86ccc71c23bf7abbea53
{"level":"info","module":"http","clientIP":"127.0.0.1:57400","method":"PATCH","path":"/v2/oci/layout/blobs/uploads/e12a21c6-9b9e-43ca-8171-8d39846e6d3a","statusCode":202,"latency":"84.450287ms","bodySize":0,"headers":{"Accept-Encoding":["gzip"],"Content-Type":["application/octet-stream"],"User-Agent":["crane/0.12.0 go-containerregistry/0.12.0"]},"goroutine":39,"caller":"zotregistry.io/zot/pkg/api/session.go:132","time":"2023-03-02T11:53:30.892583614Z","message":"HTTP API"}
{"level":"info","r.ContentLength":0,"goroutine":40,"caller":"zotregistry.io/zot/pkg/api/routes.go:1143","time":"2023-03-02T11:53:30.893216921Z","message":"DEBUG"}
{"level":"info","module":"http","clientIP":"127.0.0.1:57404","method":"PUT","path":"/v2/oci/layout/blobs/uploads/e12a21c6-9b9e-43ca-8171-8d39846e6d3a?digest=sha256%3A8fa73d8e9b247843c662dbf1f1e26a211ca0f8121d4fd858868ed10adc921b1e","statusCode":201,"latency":"135.351381ms","bodySize":0,"headers":{"Accept-Encoding":["gzip"],"Content-Length":["0"],"Content-Type":["application/octet-stream"],"User-Agent":["crane/0.12.0 go-containerregistry/0.12.0"]},"goroutine":40,"caller":"zotregistry.io/zot/pkg/api/session.go:132","time":"2023-03-02T11:53:31.028598802Z","message":"HTTP API"}
2023/03/02 11:53:31 pushed blob: sha256:8fa73d8e9b247843c662dbf1f1e26a211ca0f8121d4fd858868ed10adc921b1e
{"level":"info","module":"http","clientIP":"127.0.0.1:57404","method":"PUT","path":"/v2/oci/layout/manifests/latest","statusCode":415,"latency":"39.201µs","bodySize":404,"headers":{"Accept-Encoding":["gzip"],"Content-Length":["918"],"Content-Type":["application/vnd.docker.distribution.manifest.v2+json"],"User-Agent":["crane/0.12.0 go-containerregistry/0.12.0"]},"goroutine":40,"caller":"zotregistry.io/zot/pkg/api/session.go:132","time":"2023-03-02T11:53:31.029201909Z","message":"HTTP API"}
Error: PUT http://127.0.0.1:36345/v2/oci/layout/manifests/latest: MANIFEST_INVALID: manifest invalid; [map[mediaType:application/vnd.docker.distribution.manifest.v2+json]]
Error: pulling : parsing reference "": could not parse reference: 
Target //:upload failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 103.871s, Critical Path: 50.65s
```

**Workspace**
```
oci_pull(
    name = "nodejs_base_image",
    digest = "sha256:07027462f9f8235d7ef89f79a5f36be8345a17cccf32903fb2bdcb88e879fce9", # sha for tag 'latest-amd64'
    image = "gcr.io/distroless/nodejs18-debian11",
)
```

**BUILD.bazel**
```
js_image_layer(
    name = "layers",
    binary = "//packages/main",
    root = "/app",
    visibility = ["//visibility:__pkg__"],
)

oci_image(
    name = "server",
    architecture = "amd64",
    base = "@nodejs_base_image",
    cmd = ["/app/packages/main/main"],
    entrypoint = ["bash"],
    tars = [
        ":layers",
    ],
)

oci_push(
    name = "upload",
    image = ":server",
    repository = "myregistry.azurecr.io/myimage",
)
```

I tried to run the action with:

- `bazel run //:upload -- -tag 1`.
- I tried to hardcode `default_tags = "1"` in the `oci_push` and run `bazel run //:upload`.

I get the same error. I'm not sure if this is my fault or the issue is the manifest (`MANIFEST_INVALID: manifest invalid; [map[mediaType:application/vnd.docker.distribution.manifest.v2+json]]`)

I use:
- Bazel 5.3.2
- rules_oci 0.3.0
- rules_js 1.20.1

**Comment by thesayyn** [comment] 2023-03-02 14:13
This is happening due to the current registry (zot) rejecting docker images to be stored on it. Will be fixed once https://github.com/google/go-containerregistry/issues/1579 is fixed and there is a new release including it. in the meantime you could use a custom registry implementation demonstrated in https://github.com/bazel-contrib/rules_oci/tree/main/e2e/custom_registry

**Comment by thesayyn** [comment] 2023-03-02 14:22
Duplicate of #68

**Comment by mrmeku** [comment] 2023-03-16 20:24
There is now a new release which includes the fix: https://github.com/google/go-containerregistry/releases/tag/v0.14.0

Yay!

**Comment by thesayyn** [comment] 2023-03-16 21:48
#104 is already up working with alex to land it

**Closed** 2023-03-24 16:24 UTC
