### ISSUE TITLE
Reintroduce container_run_and_extract?

### ISSUE THREAD

**Issue by njlr** [bazel-contrib/rules_oci#545] opened 2024-04-22 16:07 UTC
I propose that we reintroduce `container_run_and_extract`. 

This was a part of `rules_docker`, which I think was unfairly maligned. I've written some thoughts below - I hope that we can foster a discussion :slightly_smiling_face: 

**Why not use a genrule?**

A `genrule` runs in the context of the host machine, which may not have the tools required to execute the rule. 

**Why not use Bazel targets for the tools?**

Sadly not everything is available with a Bazel build / rule yet, so we must fallback to pre-built binaries. An image is a kind of pre-built binary. 

**Isn't `container_run_and_extract` non-reproducible?**

It depends on how it is used. 

Note that users already have a responsibility to write reproducible rules - this would be no different.

```starlark
genrule(
  name = "time",
  outs = [ "time.txt" ],
  cmd = "date +%s > $@",
)
```

**Why not use the Docker genrule sandbox?**

AFAICT, this is an all or nothing feature - either all `genrule`s execute in a Docker sandbox or none of them do. It also appears that you must choose one image for all rules. With `container_run_and_extract`, you only pay for what you use and you can have different rules using different images. Those image can also be Bazel targets. 

**Would this require a Docker toolchain?**

From https://github.com/bazel-contrib/rules_oci/issues/132:

> requires rules_oci to declare a dependency on a docker_toolchain which we are not willing to take.

This is a fair point, and perhaps an argument for a new set of rules that builds on top of `rules_oci`. 

Is it possible for toolchains to be optional in a set of Bazel rules?

**Comment by thesayyn** [comment] 2024-05-31 17:28
> A `genrule` runs in the context of the host machine, which may not have the tools required to execute the rule.

I believe this works as intended, genrule allow you bring in your own tools by using either toolchains or simple executable targets. 

https://github.com/bazel-contrib/rules_oci/blob/13543fec47d7744fb886e636a7ca2291575d2501/examples/dockerfile/BUILD.bazel#L6-L14

using a genrule here does not necessarily mean that you download and run "the tool in an image" in a genrule, it means that you can use a genrule to invoke docker command to produce what it is that you want. 

> Why not use the Docker genrule sandbox?

Fair point, but i believe this is limitation of Bazel, rather than rules_oci. 

> Isn't `container_run_and_extract` non-reproducible?

Unfortunately, it is more nuanced than invoking the date command. by default common package managers in linux ecosystem is non-reproducible by design. This by itself is a big enough reason to not encourage users to have Dockerfile builds as a node in their code DAG. 


> Would this require a Docker toolchain?

Not having a  docker toolchain is a feature of rules_oci and we will do everything we can to not have it.

> Is it possible for toolchains to be optional in a set of Bazel rules?

Yes, you can have optional toolchains in bazel. 



All that said, what you want to do here is totally doable today similar to rules_docker,  it's just that we don't have a rule for it and we never will in a foreseeable future. 

See our dockerfile example: https://github.com/bazel-contrib/rules_oci/tree/2.x/examples/dockerfile

**Comment by thesayyn** [comment] 2024-06-08 18:13
Closing this as this is possible today without introducing a rule for this here in rules_oci. 

See:  https://github.com/bazel-contrib/rules_oci/blob/32139d8e882710c3472030e804711a4835e4428b/examples/dockerfile/BUILD.bazel#L17-L34

Refer to https://github.com/bazel-contrib/rules_oci/blob/32139d8e882710c3472030e804711a4835e4428b/examples/dockerfile/README.md

**Closed by thesayyn** 2024-06-08 18:13 UTC
Labels: need: discussion, works as intended

**Comment by njlr** [comment] 2024-07-24 12:46
It seems this example no longer exists on `main`?

**Comment by thesayyn** [comment] 2025-09-18 15:59
FWIW, we decided that this is important enough that it should be its own ruleset.

Aspect Build is going to support https://github.com/aspect-build/rules_buildx for Dockerfile support.
