### ISSUE TITLE
oci_tarball & oci_push api mismatch

### ISSUE THREAD

**Issue by LavaToaster** [bazel-contrib/rules_oci#156] opened 2023-04-14 00:42 UTC
👋 Hey There!

Something interesting I've noted is that the api for `oci_tarball` and  `oci_push` are similar but quite different.

In `oci_tarball` the `repotags` args should include the repo name and repo tag.
In `oci_push` the repository name is split out, and `repotags` is just tags and is stampable. 

Would be good to standardise 😄

**Comment by alexeagle** [comment] 2023-04-14 14:35
agreed, we usually go over all the public APIs with a fine-toothed comb before we cut a semver-stable 1.0 RC. Want to join that meeting?

**Comment by thesayyn** [comment] 2023-04-14 16:19
We decided to remove the `repository` and make oci_pull match oci_tarball.

**Comment by LavaToaster** [comment] 2023-04-14 17:02
@alexeagle I'm happy to join it.

@thesayyn Assume you mean `oci_push`? If so how will stamping change? I.E Does it need to be aware of the repository url(s) and tagging strategies now?

IMO, I would prefer repository names and tags to be separate. Though that preference may come from my experience of doing this with an [`nx plugin`](https://github.com/gperdomor/nx-tools/blob/main/packages/nx-container/docs/advanced/tags-labels.md)

**Comment by thesayyn** [comment] 2023-04-14 17:10
> Assume you mean `oci_push`

sorry. yes. 

> Does it need to be aware of the repository url(s) and tagging strategies now?

after the change you'll be able to provide fully qualified names in repotags like 

```
oci_push(
  repotags = [
      "gchr.io/org/image:latest",
      "gchr.io/orgx/imagex:latest"
  ]
)
```

which is more explicit version of what you have in `nx` matrix.

**Comment by thesayyn** [comment] 2023-04-14 17:13
i'd also be comfortable with matrix strategy similar to nx. we could introduce attributes such as `repositories = []` `tags = []` which creates a matrix of both automatically. however, since we have the desire to match the `oci_tarball` i think we should go with `repotags` approach as it is explicitly in terms of final `repositories x tags` matrix and matches oci_tarball.

**Comment by LavaToaster** [comment] 2023-04-14 17:14
Would that also change `oci_pull`'s interface to include a parseable tag/digest in the image field? (or also get called this `repotags` attribute)

Whilst I'm questioning it, why `repotags` and not just `images`?

**Comment by thesayyn** [comment] 2023-04-14 20:15
tag yes, digests no.

**Comment by alexeagle** [comment] 2023-04-17 23:46
@thesayyn if you could get to this one in the next day or so, I think it unblocks us finishing up https://docs.aspect.build/guides/rules_oci_migration

**Comment by thesayyn** [comment] 2023-04-18 12:37
> @thesayyn if you could get to this one in the next day or so, I think it unblocks us finishing up https://docs.aspect.build/guides/rules_oci_migration

sure. i'll take this first.

**Comment by thesayyn** [comment] 2023-04-18 14:20
> Though that preference may come from my experience of doing this with an [`nx plugin`](https://github.com/gperdomor/nx-tools/blob/main/packages/nx-container/docs/advanced/tags-labels.md)

BTW, the nx syntax can be easily reproducible in starlark with 

```starlark
oci_push(
   repotags = [
       "{}:{}".format(repository, tag)
       for tag in ["latest", "v1.0.0"]
       for repository in ["grc.io", "ghcr.io"]
   ]
)
```

**Comment by LavaToaster** [comment] 2023-04-18 14:25
oh that's neat

i'm not used to these maps (not sure what they're called)

**Comment by thesayyn** [comment] 2023-04-19 15:08
the repotags change is almost finished but I remembered why it doesn't match oci_tarball API.  oci_tarball#repotags must have a tag, while oci_push doesn't. 

so it's a weird case to have, but totally valid use case. 

```
oci_push(
  repotags = [
      "gchr.io/org/image@<digest>",  # this is computed automatically at runtime
      "gchr.io/orgx/imagex:latest"
  ]
)
```
so either we allow `repotags` to specify a tag optionally to indicate "push-by-digest" or we invent a placeholder string. I like neither.

cc @alexeagle

**Comment by alexeagle** [comment] 2023-05-03 23:25
I reverted #169 since it made the user experience significantly more confusing.

I think the likely resolution here is now "oci_tarball and oci_push are inherently different because of what the underlying tool allows you to express, so the API difference is intentional.

I'll let @thesayyn provide any more thoughts on it and maybe re-close this.

**Comment by thesayyn** [comment] 2023-05-04 00:09
Initially the public API for `oci_tarball` and `oci_push` was different because they inherently did different things. oci_tarball responsible for loading unto daemon and oci_push pushing to 'a' registry.

unfortunately, we had to have an attribute named `repotags` in both rule because bazel already occupied `tags` which would have been the perfect name for this.  

that said I don't see any action we could take here other than having strong documentation and better error messages in case people pass something we don't expect to those attributes.

**Comment by LavaToaster** [comment] 2023-05-04 00:12
I don't understand. Why not make `oci_tarball` match `oci_push` then?

**Comment by thesayyn** [comment] 2023-05-04 00:18
> I don't understand. Why not make `oci_tarball` match `oci_push` then?

that would limit users to being able to pass only one repository to manifest.json which can take more than one. that's something I consider a bug as we are committed to following specifications and the specification for tarball says there could be more than one repotag for each tarball.

**Comment by alexeagle** [comment] 2023-05-04 22:58
decided to have `oci_tarball#repo_tags` to match RepoTags which appears in the metadata.json
https://snyk.io/blog/container-image-formats/

and `oci_push#remote_tags` to make it clear that the tags don't get "applied" to anything in bazel-out when you `bazel build`, they are performed on the remote when the push target is `run`

**Closed by alexeagle** 2023-05-04 22:58 UTC

**Comment by blackliner** [comment] 2024-07-20 02:28
> that would limit users to being able to pass only one repository to manifest.json which can take more than one. that's something I consider a bug as we are committed to following specifications and the specification for tarball says there could be more than one repotag for each tarball.

Is it possible to specify multiple repositories/image for `oci_push`?

**Comment by alexeagle** [comment] 2024-07-20 03:41
I think this is solved by making multiple push rules in a list comprehension. You can use rules_multirun if you need a single runnable target. @thesayyn do we have an example?
