### ISSUE TITLE
Document what users should do instead of containerized build actions

### ISSUE THREAD

**Issue by alexeagle** [bazel-contrib/rules_oci#54] opened 2023-01-13 16:12 UTC
We intend to never support using a container runtime as an input to a Bazel action, because
-  it's so difficult to be hermetic (e.g. remote execution with a container runtime) 
- also difficult to be deterministic (avoiding timestamps in the output, etc).
- hard to get the container runtime for the `exec` platform (we'd need to bulid a Bazel toolchain to supply the container runtime for the right platform) and also ensure the container is built for that architecture.

Possibilities for users migrating from `run_and_commit_layer` and related rules:
- When the run_and_commit_layer is just to build a base image with 3p tools, recommend hosting their own base image, or use rules from distroless-tools
- User could wire up their own thing to use emulation
- User can still write their own rule to spawn an action that does work in a container (e.g. `run_binary` rule) - we just don't want to commit to supporting that use case.

**Comment by thesayyn** [comment] 2023-04-14 16:21
closing as duplicate of #132

**Closed by thesayyn** 2023-04-14 16:21 UTC
