### ISSUE TITLE
Question: Has anyone attempted to use this rules_oci with skaffold?

### ISSUE THREAD

**Issue by ipv1337** [bazel-contrib/rules_oci#265] opened 2023-06-14 07:01 UTC
I'm trying to replicate this workflow [here](https://skaffold.dev/docs/builders/builder-types/bazel/), but they are using the rules_docker implementation.

I'm curious if tinkering with rules_oci would work as it is implemented currently or if it will require some leg work to get going. Ultimately I'm aiming for a seemly development experience to allow our developers to test their containers in a more complete kubernetes environment without playing around with docker-compose.

Any advice or help is much appreciated. 

PS: I'm also trying to construct a more complete public example that I will write articles about also showcasing the hard work that you guys have done [here](https://github.com/BlueCentre/monorepo)

**Comment by ipv1337** [comment] 2023-06-19 23:22
I assumed so as well, but I spent several days trying to get an example working without success. I have the example work [here](https://github.com/BlueCentre/monorepo/tree/master/projects/go_devops_cli_app) if you don't mind taking a glance to see if I'm just missing something very basic.

Couple notes:
1. Skaffold requires a bazel target suffixed with .tar and that works with rules_docker without actually having a target name as such.
2. Using rules_oci approach, I just created another oci_tarball with the name suffixed with .tar to quickly test and got skaffold to stop complaining, but I ran into an interesting error.

Output:
```
user@workstation-james-vscode-uscentral1-sm:~/Workspace/gh/monorepo$ make dev_go_devops_cli_app 
skaffold dev -m go-devops-cli-app-config
WARN[0007] Could not get minikube docker env, falling back to local docker daemon: getting minikube env: running [/usr/bin/minikube docker-env --shell none -p minikube --user=skaffold]
 - stdout: "false exit code 89\n"
 - stderr: ""
 - cause: exit status 89  subtask=-1 task=DevLoop
WARN[0009] failed to detect active kubernetes cluster node platform. Specify the correct build platform in the `skaffold.yaml` file or using the `--platform` flag  subtask=-1 task=DevLoop
Generating tags...
 - go-devops-cli-app -> go-devops-cli-app:bb22ad3
Checking cache...
WARN[0010] Retrieving Bazel dependencies can take a long time the first time  subtask=-1 task=Build
 - go-devops-cli-app: Not found. Building
Starting build...
Found [minikube] context, using local docker daemon.
Building [go-devops-cli-app]...
Loading: 
Loading: 
Loading: 0 packages loaded
Analyzing: target //projects/go_devops_cli_app:tarball.tar (0 packages loaded, 0 targets configured)
Analyzing: target //projects/go_devops_cli_app:tarball.tar (75 packages loaded, 827 targets configured)
Analyzing: target //projects/go_devops_cli_app:tarball.tar (79 packages loaded, 12099 targets configured)
INFO: Analyzed target //projects/go_devops_cli_app:tarball.tar (80 packages loaded, 12602 targets configured).
INFO: Found 1 target...
INFO: Deleting stale sandbox base /home/user/.cache/bazel/_bazel_user/dc5c8e0aefc4acc300906d914a7be6f5/sandbox
[5 / 18] [Prepa] BazelWorkspaceStatusAction stable-status.txt
[7 / 18] checking cached actions
Target //projects/go_devops_cli_app:tarball.tar up-to-date:
  bazel-bin/projects/go_devops_cli_app/tarball.tar/tarball.tar
INFO: Elapsed time: 6.544s, Critical Path: 0.35s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
Cleaning up...
 - No resources found
build [go-devops-cli-app] failed: loading image into docker daemon: reading from image load response: invalid tag "go-devops-cli-app"
make: *** [Makefile:84: dev_go_devops_cli_app] Error 1
```

DISCLAIMER:
I am new to both bazel and skaffold, but I did try to look at the skaffold build bazel [code](https://github.com/GoogleContainerTools/skaffold/blob/main/pkg/skaffold/build/bazel/build.go) and compared [go_image](https://github.com/bazelbuild/rules_docker/blob/master/go/image.bzl) with [oci_tarball](https://github.com/bazel-contrib/rules_oci/blob/main/oci/defs.bzl) and I really couldn't figure out why this is not working...

**Comment by alexeagle** [comment] 2023-06-20 02:20
Sorry, I got lost in your large repo trying to understand the reproduction. Can you make a minimal one? Also note there's paid support for this project, if you just want this fixed right now :)

**Comment by alexeagle** [comment] 2023-06-20 02:20
`loading image into docker daemon: reading from image load response: invalid tag "go-devops-cli-app"` 

-> did you look in your docker daemon and see what tags are present?

**Comment by ipv1337** [comment] 2023-06-21 06:25
Thanks for your responses on this @alexeagle. Right now I'm evaluating the feasibility of Bazel, Pants, Buck, etc so I'm in no exact rush. Just seeing which one fits our needs with how we have structured our monorepo today to assess the level of effort and the pain points.

Btw also thank you for the advice about checking the docker daemon to see which tags were present. That lead me to troubleshooting from another angle trying to docker load manually which also did not work so I managed to get the right tag that docker supported.

Now onto the next step that fails a few lines down as seen [here](https://github.com/GoogleContainerTools/skaffold/blob/main/pkg/skaffold/build/bazel/build.go#L105). I'll hammer at it a bit more before giving Pants v2 a go.

If I do manage to get skaffold+bazel working to how I wanted, you may here from us looking to expand our use case and start implementing with your guy's help.

**Comment by aran** [comment] 2023-08-10 21:10
Here's a workaround courtesy of the skaffold team:

https://github.com/GoogleContainerTools/skaffold/issues/8886#issuecomment-1672403339

**Comment by thesayyn** [comment] 2024-06-09 16:39
I believe this question is now answered and fixed by upstream. https://github.com/GoogleContainerTools/skaffold/pull/9048

**Closed by thesayyn** 2024-06-09 16:39 UTC
Labels: question

**Comment by ar3s3ru** [comment] 2024-07-07 18:44
Hi folks, how does this change with `rules-oci@v2.x`, considering `oci_load` is not producing a tarball at all?

**Comment by alexeagle** [comment] 2024-07-08 01:13
oci_load still produces the tarball, but you have to explicitly request it, since it's a performance de-optimization to be avoided.
https://github.com/bazel-contrib/rules_oci/blob/2.x/docs/load.md#build-outputs

**Comment by ar3s3ru** [comment] 2024-07-08 11:36
@alexeagle thanks for the link. Is there a way to obtain a similar result to the one provided by `filegroup`, but in a Starlark rule? (Context: I have a `go_image` rule that outputs all the required OCI rules, among which there's also `oci_tarball`/`oci_load`).
