### ISSUE TITLE
FR: Build Dockerfiles with incremental cache support

### ISSUE THREAD

**Issue by stabai** [bazel-contrib/rules_oci#35] opened 2022-09-26 20:25 UTC
Feature request:
Allow Bazel to build Dockerfile images in a way that takes advantage of incremental build caching. The `dockerfile_image` rule in rules_docker contrib allows building such images, but it's incredibly slow because of the lack of build cache.

**Comment by cgrindel** [comment] 2022-10-13 17:07
Thanks for your proposal. @thesayyn has been thinking about this, as well. He will comment on this issue with his thoughts. Hopefully, we can come up with a solution that satisfies your goals.

**Comment by thesayyn** [comment] 2022-10-20 18:12
There are some problems that'll prevent us from doing this the way you want it;

- bazel has its own cache so anything that falls out of it is not tracked by bazel. therefore it would not be trivial to get the docker cache included in the bazel cache. 
- an alternative is to keep the docker build cache local to the host and let it leak into the sandbox. but this would increase the likelihood of non-hermetic builds.
- biggest drawback is that `Dockerfile` is not hermetic by design, meaning instructions such as `RUN apt-get install curl` or `make build` is not repeatable, which would lead to non-reproducible builds. 
- bazel already knows how to [cross-]compile various languages, so it doesn't make sense to delegate this task to docker.
- requires rules_oci to declare a dependency on a docker_toolchain which we are not willing to take.

I have been thinking about this issue for a while, how to tackle the problem without sacrificing a whole lot. combination of `gazelle + rules_oci` is the way to do this. to explain the idea roughly;

given a Dockerfile; 

```Dockerfile
FROM node:12

RUN apt-install curl

WORKDIR /app

COPY index.js  .

RUN yarn install --production

CMD ["node", "index.js"]

EXPOSE 3000
```
a gazelle plugin for rules_oci would translate it to;

WORKSPACE
```starlark

debian_archive(
    name = "debian_amd64_curl"
    urls = ["debian_archive_url"]
)

oci_pull(
    name = "node_12",
    repository = "index.docker.io/library/node",
    ref = "12"
)

translate_pnpm_lock(
   name = "npm",
   yarn_lock = "yarn.lock"
)
```

BUILD
```starlark

js_binary(
   name = "app",
   entry_point = "index.js"
)
oci_image(
   name = "image",
   base = "@node_12//:image", 
   tars = [
      ":app"
   ]
   workdir = "/app",
   cmd = ["index.js"],
   ports = [3000],
   
)
```

**Comment by mvgijssel** [comment] 2023-04-27 06:09
Does the `debian_archive` rule exist somewhere? As this would solve 90% of the problem for me!

**Comment by michaeljs1990** [comment] 2023-08-14 01:44
> Does the `debian_archive` rule exist somewhere? As this would solve 90% of the problem for me!

This is from the distroless repo https://github.com/GoogleContainerTools/distroless/blob/main/private/remote/debian_archive.bzl however it's not very easy to use and in order to keep your packages up to date you will need automated tooling. They have written `debian_package_manager` also located in that repo but it only works with the main repo and channels. You can modify it easily to work with other channels but if you want to do something like pull from a different repo such as postgres you will not have a fun time.

I'll spend a few more hours trying to rewrite the debian_package_manager to work with any repo but I have a feeling I might hit some other limitations shortly after. I really want to use rules_oci but might have to just go with rules_docker for the time and then work on building out the above tooling above before migrating over.

**Comment by yeukhon** [comment] 2023-11-01 14:44
I come here with a similar frustration. Understand this is not an easy problem, but it seems like it is impossible to build anything without breaking outside of bazel.

Like, to build a base image with all the years-old-wisdom packages (mysql, postgres, curl etc) we need to do this outside of bazel with vanilla dockerfile (or an alternative to docker cli such as https://buildah.io/). Upstream maintainers spent half of their lives building rpm and deb packages. It isn't as simple as just downloading a deb, we'd have to find all the required debs too...

We should find a solution together. Falling back to `rules_docker` is unreasonable because it is a dead project and it won't receive updates for newer version of bazel.

Slapping on yet another rule seems like npm's approach. While I favor keeping `rules_oci` as simple as possible, `oci_image` as a macro, which is to build an image, lacks the ability to actually run actions seems like a missed opportunity.

**Comment by thesayyn** [comment] 2023-12-12 21:48
Now that https://github.com/chainguard-dev/rules_apko exists and 
we are working on https://github.com/bazel-contrib/SIG-rules-authors/issues/88 https://github.com/GoogleContainerTools/rules_distroless this should be less frustrating.  

dockerfile_image  and container_run_and_commit are a mistake, it might be comfortable to use but it barely does the right thing. It's not platforms compatible, not-hermetic (therefore root of cache misses).
 
NOTE: Whatever `dockerfile_image` did can be done in a genrule.

**Comment by thesayyn** [comment] 2024-05-24 23:15
Closing as completed https://github.com/bazel-contrib/rules_oci/pull/570

**Closed by thesayyn** 2024-05-24 23:15 UTC
Labels: need: discussion

**Comment by thesayyn** [comment] 2025-09-18 15:59
FWIW, we decided that this is important enough that it should be its own ruleset. 

Aspect Build is going to support https://github.com/aspect-build/rules_buildx for Dockerfile support.
